apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: team-b

bases:
- ../../base

patches:
- target:
    kind: Namespace
    name: base
  patch: |-
    - op: replace
      path: /metadata/name
      value: team-b
