apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: in-cluster-install-compliance-scans
  namespace: openshift-gitops
spec:
  destination:
    namespace: in-cluster
    server: 'https://kubernetes.default.svc'
  info:
    - name: Description
      value: Deploy and configure the Compliance Scan Operator
  project: default
  source:
    path: charts/compliance-operator-full-stack
    repoURL: 'https://github.com/tjungbauer/helm-charts'
    targetRevision: main
