apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  generateName: grafana-operator-
  namespace: grafana-operator
  annotations:
    argocd.argoproj.io/sync-wave: "2" 
spec:
  targetNamespaces:
  - grafana-operator
