apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: grafana
  name: openshift-operators
spec:
  channel: v4
  installPlanApproval: Automatic
  name: grafana-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
